sudo: false
dist: xenial

services:
  - xvfb

language: python

matrix:
    include:
        - python: "3.6"
          os: linux
        - python: "2.7"
          os: linux

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - python-matplotlib
    - python-pandas
    - python-tk

before_install:
  - pip install -U pip

install:
  - pip install git+https://github.com/bendalab/audioio
  - pip install nose nose-cov python-coveralls
  - pip install -r requirements.txt

# command to run tests
script:
  - xvfb-run nosetests -vv --with-coverage --cover-package=thunderfish

after_success:
  - coveralls
