name: checks
on: [push]

jobs:
  run-checks:
    if: github.repository == 'janscience/thunderfish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout thunderfish
        uses: actions/checkout@v4
        
      - name: Setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libblas-dev liblapack-dev gfortran libsndfile1 libsndfile1-dev libffi-dev libasound2-dev python3-dev python3-tk
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install pdoc3
          pip install mkdocs
          pip install git+https://github.com/janscience/audioio.git
          pip install -r requirements.txt

      - name: Run tests
        run: python3 -m pytest -v --cov-report xml --cov-report html:cover --cov-report term --cov thunderfish tests/
        shell: bash

      - name: Build documentation
        run: ./build-docs.sh
        shell: bash
        
